version: '3.0'
services:
  dispenser-api:
    container_name: dispenser-api
    depends_on:
      - dispenser_db
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
#      - spring.datasource.url=jdbc:mysql://dispenser_db:3306/dispenser
      - MYSQL_USERNAME=dispenser
      - MYSQL_PASSWORD=dispenser
#    networks:
#      dispenser-network:

  dispenser_db:
    image: mysql:8.0
    container_name: dispenser_db
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=dispenser
        - MYSQL_PASSWORD=dispenser
        - MYSQL_USER=dispenser
#        - MYSQL_ROOT_HOST='%'
#        - MYSQL_HOST=dispenser_db
    volumes:
      - dispenser_api_data:/var/docker/mysql
#    networks:
#      dispenser-network:

volumes:
  dispenser_api_data:

#networks:
#  dispenser-network: